# 基本信息
title: Jue Hou
position: Master Student
affiliation: Xiamen University
affiliation_link: https://www.xmu.edu.cn/
email: marquis128@foxmail.com

# 搜索引擎优化（SEO）
# 以下信息用于提高网站来自搜索引擎（例如谷歌）的流量
keywords: Jue Hou, 侯爵
description: The Jue Hou's personal academic homepage.
canonical: https://marquis03.github.io/

# 链接
google_scholar: https://scholar.google.com/citations?user=GoceuAsAAAAJ
# cv_link: assets/files/curriculum_vitae.pdf
github_link: https://github.com/Marquis03
# linkedin: https://www.linkedin.com/
# twitter: https://twitter.com/

# 图片（例如，您的个人头像和网站的图标）
# "favicon"和"favicon_dark"分别用于亮色模式和暗色模式
avatar: ./assets/img/avatar.jpg
favicon: ./assets/img/xmu-logo.svg
favicon_dark: ./assets/img/xmu-logo.svg

# 页脚注释
# 可以使用此选项禁用页脚的 “由 Jekyll 和 Minimal Light 主题提供支持” 注释
enable_footnote: true

# 自动暗色模式
# 可以使用此选项禁用自动暗色主题
auto_dark_mode: true

# 字体
# 可以使用此选项在衬线字体（"Serif"）和无衬线字体（"Sans Serif"）之间选择
font: "Serif"

# Google Analytics ID
# 如果不使用 Google Analytics，请删除此项
# google_analytics:

# 将此项目用作 GitHub Pages 的远程主题
# 参考指南：https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/adding-a-theme-to-your-github-pages-site-using-jekyll
remote_theme: Marquis03/minimal-light

# 以下文件将从生成的网站中移除
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - README_zh_Hans.md
  - LICENSE
  - minimal-light.gemspec
